image: ubuntu:20.04

build:
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y make g++
    - apt-get install -y libboost-dev libboost-program-options-dev
  script:
    - make && ./bin/bfc --version

test:
  stage: test
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y make g++ gcovr
    - apt-get install -y libboost-dev libboost-test-dev
  script:
    - make test
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    reports:
      cobertura: coverage.xml
