image: ubuntu:20.04

build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y make g++
    - apt-get install -y libboost-dev libboost-test-dev
  script:
    - make && ./bin/bfc --version
    - make test