language: c++

# Use Ubuntu 14.04
sudo: required
dist: trusty

before_install:
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq make g++ libboost-test-dev

script:
    - make test
