language: c++

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - make
            - g++-5
            - libboost-test-dev

before_script:
    - export CXX="g++-5" CC="gcc-5"

script:
    - make test
