language: c++

sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - make
            - g++-5

before_script:
    - export CXX="g++-5" CC="gcc-5"
    - ls -la /usr/local
    - id
    - touch /usr/local/test

script:
    - make test
