language: c++

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - make
            - g++-5
            - libboost-test-dev

script:
    - make test
