language: c++

sudo: true

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - make
            - g++-5
          # - libboost-program-options-dev
          # - libboost-test-dev

before_install:
    # Use GCC 5 for C++14
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 10
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 10
    - sudo update-alternatives --install /usr/bin/cc  cc  /usr/bin/gcc   20
    - sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++   20
    - sudo update-alternatives --set cc  /usr/bin/gcc
    - sudo update-alternatives --set c++ /usr/bin/g++
    # Install coveralls tool
    - pip install --user cpp-coveralls

install:
    # Install recent version of Boost
    - cd ..
    - wget https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2
    - tar --bzip2 -xf boost_1_66_0.tar.bz2
    - cd boost_1_66_0
    - ./bootstrap.sh --with-libraries=program_options,test
    - sudo ./b2 -d0 install
    - sudo ldconfig
    - cd ../BFGenerator

script:
    - make && ./bin/bfc --version
    - make test

after_success:
    - coveralls --exclude test
